const classes = {
    0: "Out",
    1: "Floresta",
    2: "Leñosas cerradas",
    3: "Formação florestal",
    4: "Formação savânica",
    5: "Mangue",
    6: "Floresta inundável",
    9: "Silvicultura",
    11: "Campo alagado e área pantanosa",
    12: "Formação campestre",
    13: "Outras formações não florestais",
    15: "Pastagem",
    18: "Agricultura",
    19: "Lavoura temporária",
    20: "Cana",
    21: "Mosaico de usos",
    22: "Áreas não vegetadas",
    23: "Praia, duna e areal",
    24: "Área urbanizada",
    25: "Outras áreas não vegetadas",
    27: "Não observado",
    29: "Afloramento rochoso",
    30: "Mineração",
    31: "Aquicultura",
    32: "Apicum",
    33: "Rio, lago e oceano",
    34: "Geleira",
    35: "Cultura de palma",
    36: "Lavoura perene",
    39: "Soja",
    40: "Arroz",
    41: "Outras lavouras temporárias",
    42: "Pastizal abierto",
    43: "Pastizal cerrado",
    44: "Pastizal disperso",
    45: "Leñosas dispersas",
    46: "Café",
    47: "Citrus",
    48: "Outras lavouras perenes",
    49: "Restinga arborizada",
    57: "Cultivos simples",
    58: "Cultivos múltiples",
    62: "Algodão",
    63: "NoData"
}

export { classes }