import axios from 'axios';

// Method to send POST request
async function sendPostRequest(queue, species) {
    try {
        const url = `http://localhost:3005/${queue}`;
        const data = {
            "species": species
        };
        const response = await axios.post(url, data);
        console.log(response.data);
    } catch (error) {
        console.error('Ocorreu um erro ao enviar a requisição:', error.message);
    }
}

// Add species
const speciesToAdd = [
    "Macairea radula",
"Butia odorata",
"Kaunia rufescens",
"Trattinnickia demerarae",
"Monteverdia evonymoides",
"Hymenopus conferruminatus",
"Licania hoehnei",
"Cordia nervosa",
"Erythroxylum argentinum",
"Alchornea hilariana",
"Alchornea sidifolia",
"Abarema mataybifolia",
"Ateleia glazioveana",
"Bauhinia cinnamomea",
"Guibourtia chodatiana",
"Libidibia paraguariensis",
"Myrocarpus frondosus",
"Paloue brasiliensis",
"Platycyamus ulei",
"Poecilanthe parviflora",
"Tachigali setifera",
"Vouacapoua americana",
"Lecythis holcogyne",
"Quararibea turbinata",
"Miconia cretacea",
"Miconia pusilliflora",
"Miconia sagotiana",
"Ficus boliviana",
"Ficus clusiifolia",
"Ficus mariae",
"Ficus maximoides",
"Ficus tubulosa",
"Helicostylis turbinata",
"Naucleopsis guianensis",
"Sorocea bonplandii",
"Iryanthera grandis",
"Campomanesia xanthocarpa",
"Myrceugenia glaucescens",
"Picramnia parvifolia",
"Ruprechtia exploratricis",
"Frangula polymorpha",
"Paradrypetes subintegrifolia",
"Balfourodendron riedelianum",
"Conchocarpus acuminatus",
"Conchocarpus ruber",
"Esenbeckia febrifuga",
"Pilocarpus pennatifolius",
"Toxosiphon macropodus",
"Toxosiphon trifoliatus",
"Paullinia gigantea",
"Porocystis toulicioides",
"Talisia coriacea",
"Talisia microphylla",
"Talisia pachycarpa",
"Toulicia tomentosa",
"Pouteria brachyandra",
"Pouteria gallifructa",
"Picrasma crenata",
"Abarema levelii",
"Butia exilata",
"Bauhinia acuruana",
"Ilex paraguariensis",
"Cordia ecalyculata",
"Machaerium stipitatum",
"Allophylus guaraniticus",
"Solanum pseudoquina",
    "Plinia sebastianopolitana",
    "Plinia martinellii",
    "Connarus detersoides",
    "Stryphnodendron fissuratum",
    "Eremanthus rondoniensis",
    "Caryocar dentatum",
    "Eugenia viridiflora",
    "Melanoxylon brauna",
    "Colliguaja brasiliensis",
    "Sapium ciliatum",
    "Cassia midas",
    "Ormosia elata",
    "Eugenia choriophylla",
    "Plinia sessiliflora",
    "Siphoneugena martinellii",
    "Chamaecrista aspidiifolia",
    "Chamaecrista auris-zerdae",
    "Chamaecrista aurivilla",
    "Chamaecrista chaetostegia",
    "Chamaecrista compitalis",
    "Chamaecrista glaziovii",
    "Chamaecrista hatschbachii",
    "Chamaecrista paniculata",
    "Chamaecrista sincorana",
    "Stachytarpheta ajugifolia",
    "Stachytarpheta almasensis",
    "Stachytarpheta amplexicaulis",
    "Stachytarpheta andersonii",
    "Stachytarpheta arenaria",
    "Stachytarpheta atkinsiae",
    "Stachytarpheta bicolor",
    "Stachytarpheta brasiliensis",
    "Stachytarpheta brevibracteata",
    "Stachytarpheta bromleyana",
    "Stachytarpheta candida",
    "Stachytarpheta cassiae",
    "Stachytarpheta cearensis",
    "Stachytarpheta chapadensis",
    "Stachytarpheta chascanoides",
    "Stachytarpheta coccinea",
    "Stachytarpheta commutata",
    "Stachytarpheta confertifolia",
    "Stachytarpheta crassifolia",
    "Stachytarpheta diamantinensis",
    "Stachytarpheta discolor",
    "Stachytarpheta flavovirescens",
    "Stachytarpheta froesii",
    "Stachytarpheta ganevii",
    "Stachytarpheta glabra",
    "Stachytarpheta glandulosa",
    "Stachytarpheta glauca",
    "Stachytarpheta glazioviana",
    "Stachytarpheta grandiflora",
    "Stachytarpheta harleyi",
    "Stachytarpheta hirsutissima",
    "Stachytarpheta hispida",
    "Stachytarpheta integrifolia",
    "Stachytarpheta itambensis",
    "Stachytarpheta kriegeriana",
    "Stachytarpheta lacunosa",
    "Stachytarpheta lanata",
    "Stachytarpheta linearis",
    "Stachytarpheta longipedicellata",
    "Stachytarpheta longispicata",
    "Stachytarpheta lychnitis",
    "Stachytarpheta lythrophylla",
    "Stachytarpheta macedoi",
    "Stachytarpheta martiana",
    "Stachytarpheta mexiae",
    "Stachytarpheta microphylla",
    "Stachytarpheta minasensis",
    "Stachytarpheta mollis",
    "Stachytarpheta monachinoi",
    "Stachytarpheta oblongifolia",
    "Stachytarpheta olearyana",
    "Stachytarpheta pachystachya",
    "Stachytarpheta pohliana",
    "Stachytarpheta procumbens",
    "Stachytarpheta puberula",
    "Stachytarpheta quadrangula",
    "Stachytarpheta radlkoferiana",
    "Stachytarpheta ratteri",
    "Stachytarpheta restingensis",
    "Stachytarpheta reticulata",
    "Stachytarpheta rhomboidalis",
    "Stachytarpheta salimenae",
    "Stachytarpheta scaberrima",
    "Stachytarpheta schottiana",
    "Stachytarpheta sellowiana",
    "Stachytarpheta sericea",
    "Stachytarpheta sessilis",
    "Stachytarpheta sobraliana",
    "Stachytarpheta speciosa",
    "Stachytarpheta trispicata",
    "Stachytarpheta tuberculata",
    "Stachytarpheta vianae",
    "Stachytarpheta villosa",
    "Stachytarpheta eimaeriae",
    "Stachytarpheta lajedicola",
    "Stachytarpheta longibracteata",
    "Stachytarpheta meninii",
    "Stachytarpheta odorata",
    "Stachytarpheta praetermissa",
    "Stachytarpheta rizzoi",
    "Stachytarpheta liviae",
    "Quesnelia alborosea",
    "Quesnelia alvimii",
    "Quesnelia arvensis",
    "Quesnelia augusto-coburgii",
    "Quesnelia clavata",
    "Quesnelia conquistensis",
    "Quesnelia dubia",
    "Quesnelia edmundoi",
    "Quesnelia humilis",
    "Quesnelia imbricata",
    "Quesnelia indecora",
    "Quesnelia kautskyi",
    "Quesnelia koltesii",
    "Quesnelia lateralis",
    "Quesnelia liboniana",
    "Quesnelia marmorata",
    "Quesnelia morreniana",
    "Quesnelia quesneliana",
    "Quesnelia seideliana",
    "Quesnelia strobilispica",
    "Quesnelia testudo",
    "Quesnelia tubifolia",
    "Quesnelia violacea",
    "Quesnelia georgiizizkae",
    "Quesnelia vasconcelosiana"
]

// Trendline chart
speciesToAdd.forEach((species) => {
    sendPostRequest('conservationActions', species);
})

